import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        'concepts/overview',
        'concepts/data-sovereignty',
        'concepts/federation',
        'concepts/decentralized-identity',
        'concepts/linked-data',
        'concepts/agentic-web',
        'concepts/local-first',
        'concepts/architecture',
      ],
    },
    {
      type: 'category',
      label: 'Protocols',
      collapsed: false,
      items: [
        'protocols/overview',
        'protocols/solid',
        'protocols/activitypub',
        'protocols/nostr',
        'protocols/did',
      ],
    },
    {
      type: 'category',
      label: 'Projects',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'projects/index',
      },
      items: [
        {
          type: 'category',
          label: 'Servers',
          collapsed: true,
          items: [
            'projects/sandymount/index',
            'projects/jss/index',
            'projects/css/index',
            'projects/nss/index',
            'projects/nosdav/index',
            'projects/fedbox/index',
            'projects/microfed/index',
            'projects/strfry/index',
            'projects/mastodon/index',
            'projects/pleroma/index',
            'projects/pixelfed/index',
            'projects/peertube/index',
            'projects/lemmy/index',
            'projects/nostream/index',
          ],
        },
        {
          type: 'category',
          label: 'Specifications',
          collapsed: true,
          items: [
            'projects/solid-lite/index',
            'projects/slips/index',
            'projects/lws/index',
            'projects/did-nostr/index',
            'projects/did-key/index',
            'projects/did-web/index',
            'projects/blossom/index',
            'projects/cashu/index',
            'projects/universal-resolver/index',
            'projects/webfinger/index',
            'projects/webid/index',
            'projects/nodeinfo/index',
          ],
        },
        {
          type: 'category',
          label: 'Libraries',
          collapsed: true,
          items: [
            'projects/rdflib-js/index',
            'projects/solid-client/index',
            'projects/solid-authn/index',
            'projects/nostr-tools/index',
            'projects/nostr-components/index',
            'projects/ndk/index',
            'projects/mashlib/index',
          ],
        },
        {
          type: 'category',
          label: 'Apps & Tools',
          collapsed: true,
          items: [
            'projects/solidos/index',
            'projects/solid-chat/index',
            'projects/ditto/index',
            'projects/noskey/index',
            'projects/fonstr/index',
            'projects/nostrgit/index',
            'projects/damus/index',
            'projects/amethyst/index',
            'projects/primal/index',
            'projects/snort/index',
            'projects/coracle/index',
            'projects/habla/index',
            'projects/amber/index',
            'projects/alby/index',
            'projects/nostrudel/index',
            'projects/zapstr/index',
            'projects/highlighter/index',
            'projects/zapstream/index',
            'projects/nos2x/index',
            'projects/iris/index',
            'projects/flockstr/index',
            'projects/shopstr/index',
            'projects/penny/index',
            'projects/inrupt/index',
            'projects/wavlake/index',
            'projects/fountain/index',
            'projects/gossip/index',
            'projects/lnbits/index',
            'projects/yakihonne/index',
            'projects/satellite/index',
            'projects/0xchat/index',
            'projects/nsec-app/index',
            'projects/spring/index',
            'projects/current/index',
            'projects/plebstr/index',
            'projects/nostur/index',
            'projects/nostr-band/index',
            'projects/nostr-watch/index',
            'projects/nostr-build/index',
            'projects/njump/index',
            'projects/slidestr/index',
            'projects/flotilla/index',
            'projects/yana/index',
            'projects/listr/index',
            'projects/wikifreedia/index',
            'projects/freerse/index',
            'projects/blowater/index',
            'projects/nostr-nests/index',
            'projects/badges-page/index',
            'projects/stacker-news/index',
            'projects/zapddit/index',
            'projects/pinstr/index',
            'projects/oddbean/index',
            'projects/coop/index',
            'projects/lume/index',
            'projects/nostree/index',
            'projects/nostrcheck/index',
            'projects/openvibe/index',
            'projects/hostr/index',
            'projects/gitstr/index',
            'projects/voyage/index',
            'projects/wherostr/index',
            'projects/camelus/index',
          ],
        },
        {
          type: 'category',
          label: 'Bridges',
          collapsed: true,
          items: [
            'projects/mostr/index',
            'projects/bridgy-fed/index',
          ],
        },
        {
          type: 'category',
          label: 'Documentation',
          collapsed: true,
          items: [
            'projects/socialdocs/index',
            'projects/nostr-userguide/index',
            'projects/nostr-devguide/index',
          ],
        },
        {
          type: 'category',
          label: 'Agentic',
          collapsed: true,
          items: [
            'projects/agentic-alliance/index',
            'projects/blocktrails/index',
            'projects/web-prompts/index',
            'projects/aam/index',
            'projects/mcp/index',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        'guides/overview',
        'guides/your-first-pod',
        'guides/authentication',
        'guides/building-solid-apps',
        'guides/nostr-getting-started',
        'guides/production-deployment',
        'guides/multi-protocol',
      ],
    },
    {
      type: 'category',
      label: 'Manifesto',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'manifesto/index',
      },
      items: [
        'manifesto/principles',
      ],
    },
    {
      type: 'category',
      label: 'Community',
      collapsed: true,
      items: [
        'community/contributing',
        'community/roadmap',
      ],
    },
  ],
};

export default sidebars;
